### ISSUE TITLE
PyWaggle 0.51.0 fails on Python3 3.6 due to perf_counter_ns not exist (it exists from 3.7)

### ISSUE THREAD

**Issue by RBhupi** [waggle-sensor/pywaggle#24]
$python3 app.py 
using backwards compatible implementation of time_ns
Traceback (most recent call last):
  File "app.py", line 94, in <module>
    main(args)
  File "app.py", line 57, in main
    with plugin.timeit("plg.inf.time_ns"):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/waggle/plugin.py", line 128, in timeit
    start = time.perf_counter_ns()
AttributeError: module 'time' has no attribute 'perf_counter_ns'
$ python3 --version
Python 3.6.9

**Comment by seanshahkarami** [comment]
This is addressed as part of [release 0.51.1](https://github.com/waggle-sensor/pywaggle/releases/tag/0.51.1). pywaggle now falls back to using `perf_counter` when computing the duration in `Plugin.timeit` if `perf_counter_ns` doesn't exit.
